services: 
  reverse-proxy:
    image: traefik:latest
    command:
      # - "--providers.file.directory=/etc/traefik/dynamic"
      # - "--providers.file.watch=true"
      - "--configFile=/etc/traefik/config/static.yml"
    security_opt:
    - no-new-privileges:true
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./letsencrypt:/letsencrypt:rw # letsencrypt folder
    # - ./traefik-config/static.yml:/etc/traefik/traefik.yml 
    # - ./traefik-config/dynamic.yml:/etc/traefik/dynamic/dynamic.yml
    - ./traefik-config:/etc/traefik/config:ro # traefik-config folder
    - ./traefik-logs:/logs # traefik-logs folder
    environment:
      BASE_URL_FQDN: ${BASE_URL_FQDN}
      CLIENT_URL: ${CLIENT_URL}
    restart: always
    networks:
    - server-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: FERD
      INIT_MONGO_USERNAME: ${MONGO_USERNAME}
      INIT_MONGO_PASSWORD: ${MONGO_PASSWORD}
      INIT_MONGO_DATABASE: FERD
    volumes:
    - ./mongodb-data:/data/db
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    networks:
    - server-network
  
  server:
    image: ghcr.io/morfusee/ferd-server:latest
    environment:
      SESSION_KEY: ${SESSION_KEY}
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
      BASE_URL: ${BASE_URL}
      MONGO_DOCKER_URI: ${MONGO_DOCKER_URI}
      IS_DOCKERIZED: true
    labels:
    - "traefik.enable=true"
    # - "traefik.http.routers.server.rule=Host(`${BASE_URL_FQDN}`)"
    # - "traefik.http.routers.server.entrypoints=websecure"
    # - "traefik.http.routers.server.tls.certresolver=tlsresolver"

    # Auto update image
    - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    networks:
    - server-network
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
    - mongo

  watchtower:
    image: containrrr/watchtower
    command:
    - "--label-enable"
    - "--interval"
    - "30"
    - "--rolling-restart"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run
  #   environment:
  #     TUNNEL_TOKEN: ${TUNNEL_TOKEN}
  #   networks: # This should be set to enable http://server:3000 as a URL
  #   - server-network

networks:
  server-network:
    driver: bridge

# When reusing this compose file, please create the following folders:
# - letsencrypt
# - traefik-config
# - traefik-logs