services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: FERD
      INIT_MONGO_USERNAME: ${MONGO_USERNAME}
      INIT_MONGO_PASSWORD: ${MONGO_PASSWORD}
      INIT_MONGO_DATABASE: FERD
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
