services: 
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: FERD
      INIT_MONGO_USERNAME: ${MONGO_USERNAME}
      INIT_MONGO_PASSWORD: ${MONGO_PASSWORD}
      INIT_MONGO_DATABASE: FERD
    volumes:
    - ./mongodb-data:/data/db
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
    - server-network
  
  server:
    image: ghcr.io/morfusee/ferd-server:latest
    restart: always
    depends_on:
    - mongo
    networks:
    - server-network
    ports: 
    - "127.0.0.1:3000:3000"
    environment:
      SESSION_KEY: ${SESSION_KEY}
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
      BASE_URL: ${BASE_URL}
      MONGO_DOCKER_URI: ${MONGO_DOCKER_URI}
      IS_DOCKERIZED: true
    labels:
    - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    command:
    - "--label-enable"
    - "--interval"
    - "30"
    - "--rolling-restart"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run
  #   environment:
  #     TUNNEL_TOKEN: ${TUNNEL_TOKEN}
  #   networks: # This should be set to enable http://server:3000 as a URL
  #   - server-network

networks:
  server-network:
    driver: bridge