services: 
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: FERD
    volumes:
    - ./mongodb-data:/data/db
    restart: always
    networks:
    - traefik_proxy
  
  server:
    image: ghcr.io/morfusee/ferd-server:latest
    environment:
      SESSION_KEY: ${SESSION_KEY}
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
      BASE_URL: ${BASE_URL}
      MONGO_DOCKER_URI: ${MONGO_DOCKER_URI}
      IS_DOCKERIZED: true
    labels:
    # Since you have two replicas, you can't put all of these inside dynamic.yml :(
    # Enable Traefik for this service
    - "traefik.enable=true"

    # Router Configuration
    - "traefik.http.routers.server.rule=Host(`api.ferd.mcube.uk`)"
    - "traefik.http.routers.server.entrypoints=web"

    # Auto update image
    - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    networks:
    - traefik_proxy
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
    - mongo

  watchtower:
    image: containrrr/watchtower
    command:
    - "--label-enable"
    - "--interval"
    - "30"
    - "--rolling-restart"
    environment:
      WATCHTOWER_CLEANUP: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  traefik_proxy:
    external: true