global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  tlsresolver:
    acme:
      email: admin@mcube.uk
      storage: /letsencrypt/acme.json
      tlsChallenge: true