tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384

http:
  routers:
      server:
        rule: "Host(`{{env "BASE_URL_FQDN"}}`)"
        entryPoints:
          - websecure
        middlewares:
          # - cors
          - security
          - block-sensitive
        tls:
          certResolver: tlsresolver
        service: server
  services:
    server:
      loadBalancer:
        servers:
          - url: "http://server:3000"
  middlewares:
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PATCH
          - DELETE
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        accessControlAllowOriginList:
          - "{{env "CLIENT_URL"}}"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
    security:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
    block-sensitive:
      redirectRegex:
        regex: "^.*(\\.env|\\.git|docker-compose\\.yml|\\.htaccess|\\.htpasswd|config\\.json).*$"
        replacement: "/403"
        permanent: true